### ISSUE TITLE
As Municipality I want a user experience that matches the end vision...

### ISSUE THREAD

**Issue by pimotte** [discipl/waardepapieren#39]
... such that the demo looks more real.

**Acceptance criteria**
- [x] Button to reject draft waardepapier (mock) text: "Dit klopt niet!"
- [x] Content of pdf to match one actual waardepapier (see old waardepapieren project) 
- [x] Button to: download (functional, if low effort, otherwise mock)
- [x] Button to "Download to Apple Wallet" (mock)
- [x] Button "Afronden" that redirects to first step in wizard.

**Definition of ready**
- [x] Acceptance criteria have been formulated
- [x] Everyone on the team understands the story
- [x] Desired functionality is clear and described
- [x] Is small enough (at most 1/3 of sprint)
- [x] The method of demonstration should be clear
- [x] User story has been analyzed (with architecture, data model and technical decisions)
- [x] Recorded in GitHub and moved to Ready column

**Definition of done**
- [ ] Story satisfies acceptance criteria
- [ ] Implementation of story has been code reviewed
- [ ] Story has been automatically tested
- [ ] Story can be demonstrated using code on master branch
- [ ] Story has technical documentation
- [ ] Relevant functionality has been described in implementation guide
- [ ] Story implementation has been checked against non-functional requirements (e.g. security)
- [ ] Story implementation has been checked against architectural principles

**Comment by bkaptijn** [comment]
The product delivery screen must provide in yet a  more  professional example. Provide in better interface for download options to all kinds of wallets for instance with usage of clicking on logo's instead of red buttons. Should provide in a link to a client side standalone html5 validator app hosted from the municipalitu as well as links to the validator/wallet app in playstore/ios store with which the QR can be scanned.
